development:
  host: localhost
  port: 4000
  open_timeout: 2
  read_timeout: 3

test:
  host: localhost
  port: 4000
  open_timeout: 2
  read_timeout: 3

production:
  host: localhost
  port: 4000
  open_timeout: 2
  read_timeout: 3
